### ISSUE TITLE
Improve Calendar Component UI

### ISSUE THREAD

**Issue by waltzaround** [vaxxnz/vaxxnz#149]
As a person looking for a vaccine, I want a nicer looking calendar so that i feel the site is more trustworthy, and I am m ore likekly to look for a vaccination booking

**Describe the solution you'd like**
Calender atm is a bit messy when the days dont align up as displayed below
![Screen Shot 2021-09-11 at 7 51 04 PM](https://user-images.githubusercontent.com/9004833/132940757-9b021281-7ff9-4930-b260-4f7bf3c51897.png)

We think it would be nicer to modify the calendar so it displays as such

![Screen Shot 2021-09-11 at 7 49 04 PM](https://user-images.githubusercontent.com/9004833/132940826-6816d854-13a6-4567-a2d3-8cb4575f2c99.png)

Two possible approaches would be 
- adding divs that replicate empty boxes
- not using `lightgray` as a background, and instead using `nth-child` css selectors to draw the borders on the calendar instead

**Comment by keison-tang** [comment]
Hey @waltzaround,

I had a go at this without padding additional grid elements, here's how it looks:

![image](https://user-images.githubusercontent.com/20856129/134787194-5823664a-ad7e-48a1-9752-6b56170be00c.png)

Let me know what you think? If you still like the empty space padded with empty divs, I could try that too
Thanks

**Comment by JacksonLaw** [comment]
Hi @keison-tang, that looks great :)
It'd be good if those end boxes weren't such a dark colour. If you could take a look at changing that with empty divs or some other way I'm sure it would improve the UI a lot 👍

**Comment by keison-tang** [comment]
Hey @JacksonLaw 

Here it is with placeholder grid items. I wasn't too sure about mobile / smaller width screens since I would need to implement some sort of dynamic hiding based on how many grid cols there are (?). So, if there's less than 7 columns on display then all the extra grid items get hidden and it looks how it is atm.

<img width="807" alt="Screen Shot 2021-09-29 at 10 16 49 PM" src="https://user-images.githubusercontent.com/20856129/135240274-ae806cf2-26fd-4ab3-ac0d-08a711fc7bee.png">

**Comment by noway** [comment]
Omg, that looks awesome!

**Comment by noway** [comment]
That sounds fine, wanna open a PR?

**Comment by noway** [comment]
This has been resolved
